spring:
    application:
        name: jelly-mini
    mvc:
        throw-exception-if-no-handler-found: true
        pathmatch:
            matching-strategy: ant_path_matcher
    web:
        resources:
            add-mappings: true
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: zhangxb
        password: Canyou1317..
        url: jdbc:mysql://42.194.251.131:3306/jelly?characterEncoding=UTF-8&useSSL=false&useUnicode=true&serverTimezone=UTC
        hikari:
            minimum-idle: 10
            maximum-pool-size: 20
            max-lifetime: 120000
            connection-timeout: 30000
            idle-timeout: 30000
    servlet:
      multipart:
          max-request-size: 1024MB
          max-file-size: 1024MB
mybatis:
    type-aliases-package: org.jelly.frame
    mapper-locations: classpath*:mapper/*.xml
    configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
minio:
    endpoint: http://42.194.251.131:9000
    secure: false
    access-key: admin
    secret-key: jelly@2022
    bucket-name: jelly-bucket
#netty:
#    enable: false
#    port: 8079